version: "2"
services:
 bankstatement:
    build:
      context: ""
      dockerfile: ./Dockerfile.ubuntu
    image: bankstatement:latest
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      SERVICE_PORT: "6006"
      SERVICE_TIMEOUT: "900"
      WORKER_COUNT: "1"
    ports:
      - "6006:6006"
